name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@v1
    with:
      otp-version: '28'
      enable-eunit: false
      enable-ct: true
      ct-config: 'config/test_sys.config'
      postgres: true
      postgres-version: '17'
      postgres-db: 'pet_store_test'
